const ProjectsData = [
    // {
    //     // id: {
    //     //     type: DataTypes.INTEGER,
    //     //     primaryKey: true,
    //     //     autoIncrement: true,
    //     // },
    //     name: DataTypes.STRING,
    //     summary: DataTypes.STRING,
    //     imageURL: DataTypes.STRING,
    //     objectives: DataTypes.TEXT,
    //     futureImprovements: DataTypes.TEXT,
    //     techStack: DataTypes.TEXT,
    //     demolink: DataTypes.TEXT,
    //     githublink: DataTypes.TEXT,
    //     cta: DataTypes.TEXT
    // },
    {
        name: "Weather App",
        summary:
            "Weather app displaying current weather and forecast for a given location.",
        prviewSummary: "Weather app layout.",
        image: "weather-app-w-api.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Using emojis, setting their sizes",
            "Implementing custom styles by setting CSS properties",
        ],
        futureImprovements: [
            "Ability to enter different locations",
            "Retrieve weather data using an API",
            "Improve responsiveness for very small viewports",
            "Repalce emojis with custom icons,",
        ],
        techStack: ["HTML", "CSS", "Bootstrap"],
        demolink: "https://codepen.io/Doug-R/pen/eYyXrrB",
        githublink: "https://github.com/dougMR/weather-without-api",
        cta: "Sunny Skies Ahead",
    },
    {
        name: "News Website",
        summary: "Desktop news site.",
        prviewSummary: "Desktop layout for a news website home page.",
        image: "news-desktop-site.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Implementing custom styles by setting CSS properties",
            "Apply fonts from Google Fonts",
        ],
        futureImprovements: [
            "Make responsive.",
            "Retrieve news stories data using an API",
        ],
        techStack: ["HTML", "CSS", "Bootstrap"],
        demolink: "https://codepen.io/Doug-R/pen/rNpRbwL",
        githublink: null,
        cta: "This Just In!",
    },
    {
        name: "News Site Mobile Layout",
        summary: "Mobile news.",
        prviewSummary: "Mobile news site layout.",
        image: "news-mobile-site.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Implementing custom styles by setting CSS properties",
            "Apply fonts from Google Fonts",
        ],
        futureImprovements: [
            "Retrieve stories from a news API",
            "Make Responsive for Desktop.",
        ],
        techStack: ["HTML", "CSS", "Bootstrap"],
        demolink: "https://codepen.io/Doug-R/pen/jOYJoQL",
        githublink: null,
        cta: "Top Story!",
    },
    {
        name: "Feedback Form",
        summary: "Responsive feedback form, modeled after Google Forms.",
        prviewSummary: "Feedback form layout, based on Google forms.",
        image: "feedback-form.png",
        objectives: [
            "Practice with CSS selectors",
            "Practice with HTML form elements",
            "Layout using Bootstrap Grid",
            "Using CSS and Bootstrap to make the form responsive across viewport sizes",
        ],
        futureImprovements: [
            "Connect form to a script upon submit",
            "Add form data to a database",
            "Create and trigger a 'thankyou' screen",
        ],
        techStack: ["HTML", "CSS", "Bootstrap"],
        demolink: "https://codepen.io/Doug-R/pen/popYmGp",
        githublink: null,
        cta: "Your Opinion Matters",
    },
    {
        name: "MegaFlix Webpage",
        summary: "One of two, webpage layout modeled after a popular streaming service",
        prviewSummary: "Re-creation of a popular streaming site.",
        image: "flix-site.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Advanced layout techniques with CSS properties and Bootstrap classes",
            "Make responsive sizing / spacing from desktop to large screens",
        ],
        futureImprovements: [
            "Ability to scroll movie thumbnail rows",
            "Responsive layout change on small screens",
            "Cycle through movies/shows in 'Featured' hero section, pulling content from a database",
            "Add user profile dropdown menu",
            "Play videos",
        ],
        techStack: ["HTML", "CSS", "Bootstrap"],
        demolink: "https://www.dougroussin.com/mega-flix/",
        githublink: "https://github.com/dougMR/mega-flix",
        cta: "Action!",
    },
    {
        name: "Another Netflix Clone",
        summary: "Two of two, clone of a popular streaming service.",
        prviewSummary: "Clone of a clone.",
        image: "netflix-clone-cohort-1.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Advanced layout techniques with CSS properties",
            "Make responsive sizing / spacing from desktop to large screens",
        ],
        futureImprovements: [
            "Ability to scroll movie thumbnail rows",
            "Load separate video previews based on thumbnail selected",
            "Cycle through movies/shows in 'Featured' hero section, pulling content from a database",
            "Add user profile dropdown menu",
            "Play videos",
            "Connect to movie database",
        ],
        techStack: ["HTML", "CSS"],
        demolink: "https://www.dougroussin.com/careersInCode-netflix-clone/",
        githublink: "https://github.com/dougMR/careersInCode-netflix-clone",
        cta: "More Action!",
    },
    {
        name: "dougroussin.com",
        summary: "Portfolio site for displaying projects, big and small, front-end to back-end.",
        prviewSummary: "A portfolio site for showing projects.",
        image: "portfolio-site.png",
        objectives: [
            "Create a website for advertising oneself and one's work",
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Using CSS 'animation' property and @keyframes to create more dynamic page content",
        ],
        futureImprovements: [
            "Modular projects pages",
            "System for entering project data to create new project page",
            "Select stronger colors palette",
            "Improve copy",
        ],
        techStack: ["HTML", "CSS", "Bootstrap", "React"],
        demolink: "https://www.dougroussin.com/index.html",
        githublink: "https://github.com/dougMR/portfolio-react",
        cta: "Very Meta!",
    },
    {
        name: "Calculator",
        summary: "A Calculator App, Based on a Calculator.",
        prviewSummary: "A virtual calculator that works much like a real calculator.",
        image: "calculator-2.png",
        objectives: [
            "Think like a calculator, then write code",
            "Layout and styling using CSS",
            "'Illustrate' with CSS",
            "Apply fonts from Google Fonts",
        ],
        futureImprovements: [
            "Enable Keyboard Input",
            "Allow direct input of negative numbers : -2 * 5 rather than 0 - 2 * 5",
            "Compensate for JS decimal imprecision",
        ],
        techStack: ["HTML", "CSS", "Javascript"],
        demolink: "https://www.dougroussin.com/calculator/",
        githublink: "https://github.com/dougMR/calculator",
        cta: "It Adds Up!",
    },
    {
        name: "eval()-culator",
        summary: "A Calculator App, Using eval() for Operations.",
        prviewSummary: "A virtual calculator that eval() for operations.",
        image: "eval-culator.png",
        objectives: [
            "Build a calculator with Javascript",
            'Create a "neon" effect with CSS',
        ],
        futureImprovements: [
            "Improve key layout",
            "Limit screen's string length to stay within screen width",
            "Add decimal",
            "Compensate for JS decimal imprecision",
        ],
        techStack: ["HTML", "CSS", "Javascript"],
        demolink: "https://www.dougroussin.com/eval-culator/",
        githublink: "https://github.com/dougMR/eval-culator",
        cta: "They‘re Multiplying!",
    },
    {
        name: "Movie Seating App",
        summary: "App for Viewing and Choosing Seats in a Movie Theater.",
        prviewSummary: "A demo app for selecting seats in theaters.",
        image: "movie-seating-app.png",
        objectives: [
            "'Decorating' with CSS",
            "Using Javascript DOM to manipulate HTML page",
        ],
        futureImprovements: [
            "Connect to a database to store seat information beyond live session",
            "Create the checkout phase of the interaction",
            "Add movie preview",
        ],
        techStack: ["HTML", "CSS", "Javascript"],
        demolink: "https://www.dougroussin.com/movie-seating-selector/",
        githublink: "https://github.com/dougMR/movie-seating-selector",
        cta: "Sit Down!",
    },
    {
        name: "Weather App w/ Live Data",
        summary: "Weather app uses API to display weather by zipcode.",
        prviewSummary: "A weater app that uses an API to display weather based on zipcode.",
        image: "weather-app-w-api.png",
        objectives: [
            "Connect to API endpoints, retrieve, parse and display data",
            "Practice with CSS selectors to implement custom styles",
            "Layout using Bootstrap Grid",
        ],
        futureImprovements: [
            "User ability to add cities to pulldown.",
            "Change background sky graphic based on weather.",
        ],
        techStack: ["HTML", "CSS", "Javascript", "Bootstrap"],
        demolink: "https://www.dougroussin.com/weather-w-api-data/",
        githublink: "https://github.com/dougMR/weather-w-api-data",
        cta: "It’s Pouring data!",
    },
    {
        name: "Tic Tac Toe Game",
        summary: "Tic-tac-toe game. Play against the computer AI.",
        prviewSummary: "A tic-tac-toe game app where you play against computer AI.",
        image: "tic-tac-toe.png",
        objectives: [
            "Create a turn-based gameplay",
            "Event-driven functionality",
            "Build AI that plays tic-tac-toe with a strategy",
        ],
        futureImprovements: [
            "Improve the graphics / design.",
            "Draw line through winning squares.",
            "Add animations.",
            "Replace alerts with custom dialog panels.",
        ],
        techStack: ["HTML", "CSS", "Javascript"],
        demolink: "https://www.dougroussin.com/tic-tac-toe/",
        githublink: "https://github.com/dougMR/tic-tac-toe",
        cta: "XOXO!",
    },
    {
        name: "Tip Calculator",
        summary: "A tip calculator. It calculates tips.",
        prviewSummary: "Quick, what’s 19% of $53.17?!",
        image: "tip-calculator.png",
        objectives: [
            "Practice with CSS selectors",
            "Layout using Bootstrap Grid",
            "Work with the Javascript DOM, targeting elements for input and output.",
        ],
        futureImprovements: [
            "Percentage pulldown.",
            "Auto-choose tip percent via “How was the service?” questions.",
        ],
        techStack: ["HTML", "CSS", "Javascript", "Bootstrap"],
        demolink: "https://www.dougroussin.com/tip-calculator/",
        githublink: "https://github.com/dougMR/tip-calculator",
        cta: "It’s Gratuitous",
    },
    {
        name: "NY Times Bestsellers",
        summary: "List of New York Times Bestselling books & eBooks, in various categories.",
        prviewSummary: "A comprehensive list, across genres",
        image: "nytimes-bestsellers.png",
        objectives: [
            "Connect to NYTimes API endpoints",
            "Parse data and display results",
            "Work with CSS to build custom presentation layout",
            "Connect to sales",
        ],
        futureImprovements: [
            "Better mobile experience",
            "Add more at-a-glance data",
        ],
        techStack: ["HTML", "CSS", "Javascript", "Bootstrap", "API"],
        demolink: "https://www.dougroussin.com/NYTimes-bestsellers-list/",
        githublink: "https://github.com/dougMR/NYTimes-bestsellers-list",
        cta: "Turn the Page!",
    },
    {
        name: "Pathfinding, Brute Force",
        summary: "Trial-and-error determination of shortest path.",
        prviewSummary: "Trial-and-error process to find the shortest possible route through a set of points",
        image: "pathfinding-brute-force.png",
        objectives: [
            "Algorithmic programming",
            "Step through all permutations of a set of points",
            "Visualize the process of the brute force pathfinding algorithm",
        ],
        futureImprovements: [
            "Add timer for time elapsed & estimated duration remaining",
            "Improve CSS, to get pertinent info to stay onscreen in a visually appealing way",
        ],
        techStack: ["HTML", "CSS", "Javascript", "Canvas API"],
        demolink: "https://www.dougroussin.com/traveling-salesperson-problem-brute-force/",
        githublink: "https://github.com/dougMR/traveling-salesperson-problem-brute-force",
        cta: "Find Your Path!",
    },
    {
        name: "Pathfinding, Genetic Algorithm",
        summary: "Pathfinding with Genetic Algorithm.",
        prviewSummary: "Finding shortest routes through a set of points, using the genetic algorithm",
        image: "pathfinding-genetic.png",
        objectives: [
            "Algorithmic programming",
            "Search for shortest path through a set of points",
            "Repeatedly refine route by using best routes from previous try as seeds for routes in next try",
            "Visualize the comparison of pathfinding with brute force and genetic algorithms",
        ],
        futureImprovements: [
            "Add timer for time elapsed & estimated duration remaining",
            "Show attempted paths for the genetic algorithm, not just current best path",
            "Improve CSS, to get pertinent info to stay onscreen in a visually appealing way",
        ],
        techStack: ["HTML", "CSS", "Javascript", "Canvas API"],
        demolink: "https://www.dougroussin.com/traveling-salesperson-genetic-algorithm/",
        githublink: "https://github.com/dougMR/traveling-salesperson-genetic-algorithm",
        cta: "It’s Geneterrific!",
    },
];

export default ProjectsData;
